pipeline {
  agent any
  
  environment {
        KUBECONFIG_JENKINS  = credentials('kubeconfig')
        //IMAGE_NAME="course-catalog"
        //IMAGE_TAG="0.0.${BUILD_ID}"
        //NEXUS_SERVER="192.168.56.20:8082"
        //HTTP_PROTO="http://"
        //JENKINS_CREDEN="710f295d-1bfb-43f4-a83c-2bbfe1ea61f1"      
        //IMAGE_NAME="registry:5000/supermario"
        //IMAGE_TAG="0.0.${BUILD_ID}"
  } 

  parameters {
      choice(name:'ENVIRONMENT', choices:['HOMOLOG','PROD'], description: 'Um ambiente para executar a pipelie')
  }

  stages {

    stage('Inicializando Kubeconfig'){
      steps{
         sh 'cat $KUBECONFIG_JENKINS > ~/.kube/config' 
      }
    }
      stage('Environment') {
        steps {
          echo "Esse é um ambiente de: ${params.ENVIRONMENT}"
        }
      }    

    stage('Teste Homolog'){

      when {
          expression { 
             return params.ENVIRONMENT == 'HOMOLOG'
          }
      }

      steps{
         sh "kubectl create deploy web-app --image=nginx -n homolog"
      }
    }

    stage('Teste Prod'){

      when {
          expression { 
             return params.ENVIRONMENT == 'PROD'
          }
      }
      steps{
         sh "kubectl create deploy web-app --image=nginx -n prod"
      }
    }

  }
}
