///
pipeline{
    
    agent any
    
    options {
        
        timeout(time: 5, unit: 'SECONDS')
        timestamps()
    }

    environment {
        DIR_REPO="repo"
        LOCAL_PATH=pwd()
    }

    parameters {
        choice(name:'ENVIRONMENT', choices:['DEV','HOMOLOG','PROD'], description: 'Um ambiente para executar a pipelie')
        string(name: 'ARQUIVO', defaultValue: 'arquivo.txt', description: 'Nome do arquivo a se criar.')
        text(name: 'CONTEUDO', defaultValue: '', description: 'Entre com um conteúdo para o arquivo')
        booleanParam(name: 'CRIAR', defaultValue: true, description: 'Criar ou não o arquivo?')
    }
    
    stages {
        
        stage ('OS Release'){
            steps{
                sh 'cat /etc/*release'
            }
        }
        stage ('Listar variaveis Jenkins'){
            steps{
                echo "$WORKSPACE"
                echo "$BUILD_ID"
                echo "$BUILD_DISPLAY_NAME"
            }
        }

        stage ('Listar variaveis de ambiente'){
            steps{
                echo "DIR_REPO = ${DIR_REPO}"
                echo "LOCAL_PATH = ${LOCAL_PATH}"
            }
        }

        stage ('Parametros do Ambiente'){
            steps{
                echo "Arquivo a se criar: ${params.ARQUIVO}"
               echo "Conteúdo do arquivo: ${params.CONTEUDO}"
            }
        }        
    }
    post{
        
        always {
            
            echo "Pipeline finalizado"
        }
        
        success {
            echo "Pipeline finalizado com sucesso"
        }
        
        failure {
            echo "Pipeline finalizado com falha"
        }
    }
}
