pipeline {
    agent any

    environment{
        KUBECONFIG_JEKINS = credentials('kubeconfig')
    }

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['HOMOLOG', 'PROD'], description: 'Um ambiente para executar a pipline' )
    }

    stages{
        stage('Inicializando kubeconfig'){
            steps{
                sh 'cat $KUBECONFIG_JEKINS > ~/.kube/config'
            }
        }

        stage('ENVIRONMENT'){
            steps{
                echo "Esse é um ambiente de: ${params.ENVIRONMENT}"
            }
        }

        stage('Listando Nodes'){
            steps{
                sh 'kubectl get nodes'
            }
        }

        stage('Deploy Homolog'){
            when{
                return params.ENVIRONMENT == HOMOLOG
            }
            steps{
                sh 'kubectl -n homolog create deploy supermario --image=pengbai/docker-supermario'
            }
        }         

        stage('Deploy PROD'){
            when{
                return params.ENVIRONMENT == PROD
            }
            steps{
                sh 'kubectl -n prod create deploy supermario --image=pengbai/docker-supermario'
            }
        } 

    }

}